version: '3.8'

services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: timetable
      MYSQL_USER: user
      MYSQL_PASSWORD: timetable
    ports:
      - "7901:3306"